Source code for OpenFOAM 1.5, without third-party source code and generated data ('lnInclude', 'html' and '*.jar').

diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2007 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 1991-2008 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -30,40 +30,57 @@
 #     General, easy to use make system for multi-platform development.
 #
 #------------------------------------------------------------------------------
+Script=${0##*/}
+
+usage() {
+   while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+   cat<<USAGE
+usage: $Script [dir]
+       $Script target [dir [MakeDir]]
+
+A general, easy-to-use make system for multi-platform development
+
+The 'target' is a Makefile target:
+    e.g., Make/linux64GccDPOpt/fvMesh.o
+
+  or a special target:
+    all       all subdirectories
+    exe       build statically linked executable
+    lib       build statically linked archive lib (.a)
+    libso     build dynamically linked lib (.so)
+    libo      build statically linked lib (.o)
+    jar       build Java jar
+
+USAGE
+   exit 1
+}
+
+# provide immediate help
+if [ "$1" = "-h" -o "$1" = "-help" ]; then
+   usage
+fi
+
+
+#
 # check environment variables
-#------------------------------------------------------------------------------
+#
+for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+do
+   eval test "\$$check" || {
+      echo "$Script error"
+      echo "    environment variable \$$check not set"
+      exit 1
+   }
+done
 
-if [ ! "$WM_OPTIONS" ]
-then
-    echo $0: 'environment variable $WM_OPTIONS not set, exiting !'
-    exit 1
-fi
-
-
-if [ ! "$WM_LINK_LANGUAGE" ]
-then
-    echo $0: 'environment variable $WM_LINK_LANGUAGE not set, exiting !'
-    exit 1
-fi
-
-
-if [ ! "$WM_DIR" ]
-then
-    echo 'wmake : environment variable $WM_DIR not set, exiting !'
-    exit 1
-fi
-
-
-if [ ! "$WM_PROJECT" -o ! "$WM_PROJECT_DIR" ]
-then
-    if [ $# != 1 -o "$1" != "exe" ]
-    then
-        echo $0: 'environment variable $WM_PROJECT'
-        echo ' or $WM_PROJECT_DIR  not set'
-        echo '        for building project library or executable, exiting !'
-        exit 1
-    fi
-fi
+# when compiling anything but a standalone exe,
+# WM_PROJECT and WM_PROJECT_DIR must be set
+[ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
+   echo "$Script error"
+   echo "    environment variable \$WM_PROJECT or \$WM_PROJECT_DIR not set"
+   echo  "   while building project library or executable"
+   exit 1
+}
 
 
 #------------------------------------------------------------------------------
@@ -72,9 +89,16 @@ fi
 
 make="make"
 
+# set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
+if [ -z "$WM_NCOMPPROCS" -a -n "$WM_HOSTS" -a -n "$WM_SCHEDULER" ]
+then
+   WM_NCOMPPROCS=$(wmakeScheduler -count)
+   [ $? -eq 0 ] || unset WM_NCOMPPROCS
+fi
+
 if [ "$WM_NCOMPPROCS" ]
 then
-    if [ "$WM_NCOMPPROCS" -ne 1 -a ! "$MAKEFLAGS" ]
+    if [ "$WM_NCOMPPROCS" -gt 1 -a ! "$MAKEFLAGS" ]
     then
         lockDir=$HOME/.wmakeScheduler
 
@@ -92,62 +116,39 @@ fi
 
 #------------------------------------------------------------------------------
 # check arguments and change to the directory in which to run wmake
-#
-# wmake
-# wmake dir
-# wmake target dir
-# wmake target dir MakeDir
-#
-# target is one of the targets in the Makefile
-# (e.g. Make/linuxAMD64Gcc4DPOpt/fvMesh.o) or one of the special targets:
-#   lib     : build statically linked lib (.a)
-#   libso   : build dynamically linked lib (.so)
-#   libo    : ?
-#   jar     : build Java jar
-#   exe     : build statically linked executable
-#   project : ?
-#   all     : all subdirectories
 #------------------------------------------------------------------------------
 
-makeOption=""
-dir="_"
+unset dir makeOption
+MakeDir=Make
 
 if [ $# -ge 1 ]
 then
-    if [ -d $1 ]
-    then
-        dir=$1
-    else
-        makeOption=$1
-    fi
-fi
+   if [ -d "$1" ]
+   then
+      dir=$1
+   else
+      makeOption=$1
+   fi
 
-if [ $# -ge 2 ]
-then
-    dir=$2
-fi
+   if [ $# -ge 2 ]
+   then
+      dir=$2
+   fi
 
-if [ $dir != "_" ]
-then
-    if [ -d $dir ]
-    then
-        cd $dir
-    else
-        echo $0: directory $dir does not exist
-        exit 1
-    fi
-fi
+   # alternative name for the Make sub-directory
+   if [ $# -ge 3 ]
+   then
+      MakeDir=$3
+   fi
 
-
-#------------------------------------------------------------------------------
-# Check if there is a special name provided for the Make sub-directory
-#------------------------------------------------------------------------------
-
-if [ $# = 3 ]
-then
-    MakeDir=$3
-else
-    MakeDir=Make
+   if [ "$dir" ]
+   then
+      cd $dir 2>/dev/null || {
+         echo "$Script error"
+         echo "    could not change to directory '$dir'"
+         exit 1
+      }
+   fi
 fi
 
 
@@ -155,7 +156,7 @@ fi
 # Recurse the application directories tree
 #------------------------------------------------------------------------------
 
-if [ "$makeOption" = "all" ]
+if [ "$makeOption" = all ]
 then
     if [ -e Allwmake ]
     then
@@ -163,7 +164,8 @@ then
         exit $?
     elif [ ! -d $MakeDir ]
     then
-        $make -f $WM_DIR/MakefileApps FOAM_APPS="`find . -maxdepth 1 \( -type d -a ! -name "." -a ! -name "Make" \)  -printf "%f "`"
+        $make -k -f $WM_DIR/MakefileApps \
+            FOAM_APPS="`find . -maxdepth 1 \( -type d -a ! -name "." -a ! -name "Optional" -a ! -name "Make" \)  -printf "%f "`"
         exit $?
     fi
 
@@ -180,28 +182,30 @@ fi
 
 if [ ! -d $MakeDir ]
 then
-    echo $0: cannot make, $MakeDir directory does not exist
-    exit 1
+   echo "$Script error"
+   echo "    '$MakeDir' directory does not exist"
+   exit 1
 fi
 
 if [ ! -r $MakeDir/files ]
 then
-    echo $0: cannot make, file $MakeDir/files does not exist
-    exit 1
+   echo "$Script error"
+   echo "    file '$MakeDir/files' does not exist"
+   exit 1
 fi
 
-# Spawn a sub-shell and unset MAKEFLAGS in that sub-shell to stop avoid
+# Spawn a sub-shell and unset MAKEFLAGS in that sub-shell to avoid
 # files and options being built in parallel
 (
-  cd $MakeDir
-  unset MAKEFLAGS
-  make -s -f $WM_DIR/MakefileOptions
-  make -s -f $WM_DIR/MakefileFiles allFiles
+   cd $MakeDir
+   unset MAKEFLAGS
+   make -s -f $WM_DIR/MakefileOptions
+   make -s -f $WM_DIR/MakefileFiles allFiles
 )
 
 
 #------------------------------------------------------------------------------
-# Check the $OBJECTS_DIR = $MakeDir/$WM_OPTIONS/objectFiles file 
+# Check the $OBJECTS_DIR = $MakeDir/$WM_OPTIONS/objectFiles file
 # was created successfully
 #------------------------------------------------------------------------------
 
@@ -209,8 +213,9 @@ OBJECTS_DIR=$MakeDir/$WM_OPTIONS
 
 if [ ! -r $OBJECTS_DIR/objectFiles ]
 then
-    echo $0: cannot make, file $OBJECTS_DIR/objectFiles was not created successfully
-    exit 1
+   echo "$Script error"
+   echo "    file '$OBJECTS_DIR/objectFiles' was not created successfully"
+   exit 1
 fi
 
 
@@ -220,10 +225,11 @@ fi
 
 touch $OBJECTS_DIR/dontIncludeDeps
 
-if [ "$makeOption" = "lib" -o "$makeOption" = "libso" -o "$makeOption" = "libo" ]
-then
-    $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps lnInclude/uptodate
-fi
+case "$makeOption" in
+lib | libso | libo )
+   $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps lnInclude/uptodate
+   ;;
+esac
 
 $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps $OBJECTS_DIR/dependencies
 
